version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-network

  backend1:
    build: ./backend
    container_name: backend1
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoDB
    networks:
      - todo-network

  backend2:
    build: ./backend
    container_name: backend2
    restart: always
    ports:
      - "5002:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoDB
    networks:
      - todo-network

  backend3:
    build: ./backend
    container_name: backend3
    restart: always
    ports:
      - "5003:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoDB
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongo_data:
